package types

const (
	LOGIN_ATTEMPT_SUCCESS     = 1
	LOGIN_ATTEMPT_MAX_REACHED = 2
	LOGIN_ATTEMPT_FAILED      = 3

	USER_STATUS_ACTIVE   = 1
	USER_STATUS_INACTIVE = 2
	USER_STATUS_PENDING  = 3
	USER_STATUS_BANNED   = 4

	USER_PASSWORD_RESET_STATUS_ACTIVE   = 1
	USER_PASSWORD_RESET_STATUS_INACTIVE = 2

	USER_ACTIVATION_TOKEN_STATUS_ACTIVE   = 1
	USER_ACTIVATION_TOKEN_STATUS_INACTIVE = 2

	USER_STATE_INITIAL = 1

	EMAIL_STATUS_SUCCESS = 1
	EMAIL_STATUS_FAILED  = 2
)
