package types

const (
	ERROR_CODE_REQUEST_INVALID        = ""
	ERROR_CODE_REQUEST_PARAMS_INVALID = ""
	ERROR_CODE_INTERNAL_SERVER        = ""

	ERROR_CODE_TOKEN_INCORRECT     = ""
	ERROR_CODE_TOKEN_ALREADY_USED  = ""
	ERROR_CODE_TOKEN_EXPIRED       = ""
	ERROR_CODE_TOKEN_REVOKED       = ""
	ERROR_CODE_TOKEN_NOT_AVAILABLE = ""

	ERROR_CODE_ACCOUNT_ACTIVE   = ""
	ERROR_CODE_ACCOUNT_INACTIVE = ""
	ERROR_CODE_ACCOUNT_PENDING  = ""
	ERROR_CODE_ACCOUNT_BANNED   = ""

	ERROR_CODE_USERNAME_NOT_AVAILABLE         = ""
	ERROR_CODE_USERNAME_INCORRECT             = ""
	ERROR_CODE_USERNAME_OR_PASSWORD_INCORRECT = ""

	ERROR_CODE_MAX_ATTEMPT_REACHED = ""
)
