// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/loganrk/user-vault/internal/core/port (interfaces: Middleware)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// ValidateApiKey mocks base method.
func (m *MockMiddleware) ValidateApiKey() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateApiKey")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateApiKey indicates an expected call of ValidateApiKey.
func (mr *MockMiddlewareMockRecorder) ValidateApiKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateApiKey", reflect.TypeOf((*MockMiddleware)(nil).ValidateApiKey))
}

// ValidateRefreshToken mocks base method.
func (m *MockMiddleware) ValidateRefreshToken() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefreshToken")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateRefreshToken indicates an expected call of ValidateRefreshToken.
func (mr *MockMiddlewareMockRecorder) ValidateRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefreshToken", reflect.TypeOf((*MockMiddleware)(nil).ValidateRefreshToken))
}
