// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/loganrk/user-vault/internal/core/domain"
)

// MockUserSvr is a mock of UserSvr interface.
type MockUserSvr struct {
	ctrl     *gomock.Controller
	recorder *MockUserSvrMockRecorder
}

// MockUserSvrMockRecorder is the mock recorder for MockUserSvr.
type MockUserSvrMockRecorder struct {
	mock *MockUserSvr
}

// NewMockUserSvr creates a new mock instance.
func NewMockUserSvr(ctrl *gomock.Controller) *MockUserSvr {
	mock := &MockUserSvr{ctrl: ctrl}
	mock.recorder = &MockUserSvrMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSvr) EXPECT() *MockUserSvrMockRecorder {
	return m.recorder
}

// ForgotPassword mocks base method.
func (m *MockUserSvr) ForgotPassword(ctx context.Context, req domain.UserForgotPasswordClientRequest) (domain.UserForgotPasswordClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, req)
	ret0, _ := ret[0].(domain.UserForgotPasswordClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockUserSvrMockRecorder) ForgotPassword(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockUserSvr)(nil).ForgotPassword), ctx, req)
}

// Login mocks base method.
func (m *MockUserSvr) Login(ctx context.Context, req domain.UserLoginClientRequest) (domain.UserLoginClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(domain.UserLoginClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserSvrMockRecorder) Login(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserSvr)(nil).Login), ctx, req)
}

// Logout mocks base method.
func (m *MockUserSvr) Logout(ctx context.Context, req domain.UserLogoutClientRequest) (domain.UserLogoutClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, req)
	ret0, _ := ret[0].(domain.UserLogoutClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockUserSvrMockRecorder) Logout(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockUserSvr)(nil).Logout), ctx, req)
}

// OAuthLogin mocks base method.
func (m *MockUserSvr) OAuthLogin(ctx context.Context, req domain.UserOAuthLoginClientRequest) (domain.UserLoginClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuthLogin", ctx, req)
	ret0, _ := ret[0].(domain.UserLoginClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// OAuthLogin indicates an expected call of OAuthLogin.
func (mr *MockUserSvrMockRecorder) OAuthLogin(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthLogin", reflect.TypeOf((*MockUserSvr)(nil).OAuthLogin), ctx, req)
}

// RefreshToken mocks base method.
func (m *MockUserSvr) RefreshToken(ctx context.Context, req domain.UserRefreshTokenClientRequest) (domain.UserRefreshTokenClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, req)
	ret0, _ := ret[0].(domain.UserRefreshTokenClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockUserSvrMockRecorder) RefreshToken(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockUserSvr)(nil).RefreshToken), ctx, req)
}

// Register mocks base method.
func (m *MockUserSvr) Register(ctx context.Context, req domain.UserRegisterClientRequest) (domain.UserRegisterClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(domain.UserRegisterClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserSvrMockRecorder) Register(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserSvr)(nil).Register), ctx, req)
}

// ResendVerification mocks base method.
func (m *MockUserSvr) ResendVerification(ctx context.Context, req domain.UserResendVerificationClientRequest) (domain.UserResendVerificationClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerification", ctx, req)
	ret0, _ := ret[0].(domain.UserResendVerificationClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// ResendVerification indicates an expected call of ResendVerification.
func (mr *MockUserSvrMockRecorder) ResendVerification(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerification", reflect.TypeOf((*MockUserSvr)(nil).ResendVerification), ctx, req)
}

// ResetPassword mocks base method.
func (m *MockUserSvr) ResetPassword(ctx context.Context, req domain.UserResetPasswordClientRequest) (domain.UserResetPasswordClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, req)
	ret0, _ := ret[0].(domain.UserResetPasswordClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockUserSvrMockRecorder) ResetPassword(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockUserSvr)(nil).ResetPassword), ctx, req)
}

// VerifyUser mocks base method.
func (m *MockUserSvr) VerifyUser(ctx context.Context, req domain.UserVerifyClientRequest) (domain.UserVerifyClientResponse, domain.ErrorRes) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUser", ctx, req)
	ret0, _ := ret[0].(domain.UserVerifyClientResponse)
	ret1, _ := ret[1].(domain.ErrorRes)
	return ret0, ret1
}

// VerifyUser indicates an expected call of VerifyUser.
func (mr *MockUserSvrMockRecorder) VerifyUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUser", reflect.TypeOf((*MockUserSvr)(nil).VerifyUser), ctx, req)
}
