// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/loganrk/user-vault/internal/core/port (interfaces: Utils)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUtils is a mock of Utils interface.
type MockUtils struct {
	ctrl     *gomock.Controller
	recorder *MockUtilsMockRecorder
}

// MockUtilsMockRecorder is the mock recorder for MockUtils.
type MockUtilsMockRecorder struct {
	mock *MockUtils
}

// NewMockUtils creates a new mock instance.
func NewMockUtils(ctrl *gomock.Controller) *MockUtils {
	mock := &MockUtils{ctrl: ctrl}
	mock.recorder = &MockUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtils) EXPECT() *MockUtilsMockRecorder {
	return m.recorder
}

// GenerateOTPString mocks base method.
func (m *MockUtils) GenerateOTPString(arg0 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateOTPString", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateOTPString indicates an expected call of GenerateOTPString.
func (mr *MockUtilsMockRecorder) GenerateOTPString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateOTPString", reflect.TypeOf((*MockUtils)(nil).GenerateOTPString), arg0)
}

// GenerateString mocks base method.
func (m *MockUtils) GenerateString(arg0 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateString", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateString indicates an expected call of GenerateString.
func (mr *MockUtilsMockRecorder) GenerateString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateString", reflect.TypeOf((*MockUtils)(nil).GenerateString), arg0)
}

// GenerateUUID mocks base method.
func (m *MockUtils) GenerateUUID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUUID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateUUID indicates an expected call of GenerateUUID.
func (mr *MockUtilsMockRecorder) GenerateUUID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUUID", reflect.TypeOf((*MockUtils)(nil).GenerateUUID))
}
