package constant

const (
	LOGIN_ATTEMPT_SUCCESS     = 1
	LOGIN_ATTEMPT_MAX_REACHED = 2
	LOGIN_ATTEMPT_FAILED      = 3

	USER_STATUS_ACTIVE   = 1
	USER_STATUS_INACTIVE = 2
	USER_STATUS_PENDING  = 3
	USER_STATUS_BANNED   = 4

	USER_PASSWORD_RESET_STATUS_ACTIVE   = 1
	USER_PASSWORD_RESET_STATUS_INACTIVE = 2

	USER_STATE_INITIAL = 1

	USER_ACTIVATION_TOKEN_STATUS_ACTIVE   = 1
	USER_ACTIVATION_TOKEN_STATUS_INACTIVE = 2

	REFRESH_TOKEN_TYPE_ROTATING = "rotating"
	REFRESH_TOKEN_TYPE_STATIC   = "static"

	TOKEN_TYPE_ACTIVATION     = 1
	TOKEN_TYPE_PASSWORD_RESET = 2
	TOKEN_TYPE_REFRESH        = 3
)

const (
	USER_ACTIVATION_TOKEN_MACRO    = "{{token}}"
	USER_ACTIVATION_LINK_MACRO     = "{{link}}"
	USER_ACTIVATION_NAME_MACRO     = "{{name}}"
	USER_ACTIVATION_APP_NAME_MACRO = "{{appName}}"

	USER_PASSWORD_RESET_TOKEN_MACRO    = "{{token}}"
	USER_PASSWORD_RESET_LINK_MACRO     = "{{link}}"
	USER_PASSWORD_RESET_NAME_MACRO     = "{{name}}"
	USER_PASSWORD_RESET_APP_NAME_MACRO = "{{appName}}"

	USER_ACTIVATION_EMAIL_SUBJECT     = "{{appName}} - Activate your account"
	USER_PASSWORD_RESET_EMAIL_SUBJECT = "{{appName}} - Password reset request"
)
